/*
 * Meeting Scheduler API
 * API for scheduling and managing meetings with multiple proposed time slots.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.model;


import org.junit.jupiter.api.Test;


/**
 * Model tests for Attendee
 */
public class AttendeeTest {
    private final Attendee model = new Attendee();

    /**
     * Model tests for Attendee
     */
    @Test
    public void testAttendee() {
        // TODO: test Attendee
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'person'
     */
    @Test
    public void personTest() {
        // TODO: test person
    }

    /**
     * Test the property 'availabilities'
     */
    @Test
    public void availabilitiesTest() {
        // TODO: test availabilities
    }

}
