/*
 * Meeting Scheduler API
 * API for scheduling and managing meetings with multiple proposed time slots.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.model;

import com.example.model.AttendeeAvailabilities;

import org.junit.jupiter.api.Test;


/**
 * Model tests for AttendeeAvailabilities
 */
public class AttendeeAvailabilitiesTest {
    private final AttendeeAvailabilities model = new AttendeeAvailabilities();

    /**
     * Model tests for AttendeeAvailabilities
     */
    @Test
    public void testAttendeeAvailabilities() {
        // TODO: test AttendeeAvailabilities
    }

    /**
     * Test the property 'slotId'
     */
    @Test
    public void slotIdTest() {
        // TODO: test slotId
    }

    /**
     * Test the property 'availability'
     */
    @Test
    public void availabilityTest() {
        // TODO: test availability
    }

}
