/*
 * Meeting Scheduler API
 * API for scheduling and managing meetings with multiple proposed time slots.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.model;


import org.junit.jupiter.api.Test;


/**
 * Model tests for AttendeePerson
 */
public class AttendeePersonTest {
    private final AttendeePerson model = new AttendeePerson();

    /**
     * Model tests for AttendeePerson
     */
    @Test
    public void testAttendeePerson() {
        // TODO: test AttendeePerson
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

}
