/*
 * Meeting Scheduler API
 * API for scheduling and managing meetings with multiple proposed time slots.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.model;


import org.junit.jupiter.api.Test;


/**
 * Model tests for Meeting
 */
public class MeetingTest {
    private final Meeting model = new Meeting();

    /**
     * Model tests for Meeting
     */
    @Test
    public void testMeeting() {
        // TODO: test Meeting
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'scheduleName'
     */
    @Test
    public void scheduleNameTest() {
        // TODO: test scheduleName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'validUntil'
     */
    @Test
    public void validUntilTest() {
        // TODO: test validUntil
    }

    /**
     * Test the property 'timeslots'
     */
    @Test
    public void timeslotsTest() {
        // TODO: test timeslots
    }

    /**
     * Test the property 'responses'
     */
    @Test
    public void responsesTest() {
        // TODO: test responses
    }

}
